services:
  - type: web
    name: github-telegram-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 10000  # Matches Render's free tier default
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here  # Set in Render dashboard
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here    # Set in Render dashboard
      - key: GITHUB_WEBHOOK_SECRET
        value: your_webhook_secret  # Set in Render dashboard