services:
  - type: web
    name: github-telegram-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_actual_token_here  # ← Set in dashboard
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here       # ← Set in dashboard
      - key: GITHUB_WEBHOOK_SECRET
        value: your_generated_secret   # ← Set in dashboard
      - key: PORT
        value: 8000